name: Deploy Github Pages

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: npm install and build
        run: |
          npm ci
          npm run build --deploy-url /${{ github.event.repository.name }}
        env:
          CI: ${{ true }}

      - name: Upload artifact for github pages
        uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: dist/sw/*

  github-pages:
    needs: build
    runs-on: ubuntu-latest
    concurrency: github-pages
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: gh-pages
      
      - name: Remove current branch files
        run: rm -rf

      - name: Retrieve github pages artifact
        uses: actions/download-artifact@v3
        with:
          name: github-pages

      - name: Commit files
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add .
          git commit -m "Deploy master branch"
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages